"""Sync static HTML templates and file:// data snapshots without dependencies."""

import argparse
import json
import re
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
EXHIBITS = (
    "attn_cmp", "ramnet_arch", "product_softmax", "cape",
    "gsu", "cal_pipeline", "niah_probe", "head_probe",
)
DATA = {
    "data/experiments.json": ("data/experiments.js", "ramnetExperiments"),
    "data/probes/niah_traces.json": ("data/probes/niah_traces.js", "ramnetNiahTraces"),
    "data/probes/niah_slot_maps.json": ("data/probes/niah_slot_maps.js", "ramnetNiahSlotMaps"),
    "data/probes/head_traces.json": ("data/probes/head_traces.js", "ramnetHeadTraces"),
}


def exhibit_markup(name):
    source = (ROOT / "animations" / f"{name}.html").read_text(encoding="utf-8")
    body = re.search(r'<body\b([^>]*)>(.*?)</body>', source, re.I | re.S)
    if not body:
        raise ValueError(f"Missing body: {name}")
    classes = re.search(r'\bclass="([^"]+)"', body.group(1))
    if not classes:
        raise ValueError(f"Missing body class: {name}")
    markup = re.sub(r'<(?:no)?script\b[^>]*>.*?</(?:no)?script>', '', body.group(2), flags=re.I | re.S).strip()
    styles = ([f"animations/{name}.css?v=palette-config-20261002c", "assets/embed.css?v=palette-config-20261002c"]
              if name not in ("niah_probe", "head_probe") else ["assets/probes.css?v=palette-config-20261002c"])
    return {"bodyClass": classes.group(1), "html": markup, "styles": styles}


def current_registry():
    source = (ROOT / "assets/exhibit-markup.js").read_text(encoding="utf-8")
    return json.loads(source.split("=", 1)[1].strip().removesuffix(";"))


def normalized(markup):
    return re.sub(r">\s+<", "><", markup.strip())


def current_data(path):
    source = path.read_text(encoding="utf-8")
    return json.loads(source.split("=", 1)[1].strip().removesuffix(";"))


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="Report stale generated files without writing")
    args = parser.parse_args()
    expected = {name: exhibit_markup(name) for name in EXHIBITS}
    try:
        current = current_registry()
    except (OSError, ValueError, IndexError):
        current = {}
    stale = [name for name in EXHIBITS if name not in current or
             expected[name]["bodyClass"] != current[name]["bodyClass"] or
             expected[name]["styles"] != current[name]["styles"] or
             normalized(expected[name]["html"]) != normalized(current[name]["html"])]
    if stale:
        print("Exhibit templates differ:", ", ".join(stale))
        if not args.check:
            output = "// Generated by tools/sync_static.py from animations/*.html.\n"
            output += "window.RamnetExhibitMarkup = " + json.dumps(expected, ensure_ascii=False, separators=(",", ":")) + ";\n"
            (ROOT / "assets/exhibit-markup.js").write_text(output, encoding="utf-8")

    stale_data = []
    for source_name, (snapshot_name, global_name) in DATA.items():
        source = ROOT / source_name
        snapshot = ROOT / snapshot_name
        value = json.loads(source.read_text(encoding="utf-8"))
        if source_name == "data/experiments.json":
            for table, groups in value["tables"].items():
                width = len(value["columns"][table])
                for group in groups:
                    for row in group["rows"]:
                        if len(row["values"]) != width:
                            raise ValueError(f"{table}: {row['model']} has {len(row['values'])} values; expected {width}")
        try:
            matches = current_data(snapshot) == value
        except (OSError, ValueError, IndexError):
            matches = False
        if matches:
            continue
        stale_data.append(source_name)
        if not args.check:
            output = f"// Generated by tools/sync_static.py from {source.name}.\n"
            output += f"window.{global_name} = {json.dumps(value, ensure_ascii=False, separators=(',', ':'))};\n"
            snapshot.write_text(output, encoding="utf-8")
    if stale_data:
        print("Data snapshots differ:", ", ".join(stale_data))
    if args.check and (stale or stale_data):
        raise SystemExit(1)
    if not stale and not stale_data:
        print("Static assets are in sync.")


if __name__ == "__main__":
    main()
